### ISSUE TITLE
Using SQLite with Node 2.2.1+ backend and QuickStart does not sync

### ISSUE THREAD

**Issue by jamesmontemagno** [Azure/azure-mobile-apps-node#496]
We have narrowed down the issue to using the Mobile Apps Quick Start with a SQLite backend that the dates are off and the odata query does not complete so syncing between two devices does not work at all. The data goes into the backend, but retrieving it fails.

Simply create a new Quick Start app and use this sample app: https://github.com/xamarin/dev-days-labs/tree/master/Demos/app-tasks or even the one we ship. 

You will see the first sync down to a device works as it pulls all the data regardless, but after that sync will fail to work.

We believe that is has to do with: https://github.com/Azure/azure-mobile-apps-node/commit/322c61a85132989ff5e99cc0c0dbaf0e4a5898a7

As soon as we configure a real SQL Azure database and server then it works just fine.

When this is fixed we should also push out a fix to the Quick Start template.

**Comment by danderson00** [comment]
This was a buggy release - queries against createdAt and updateAt using the SQLite data provider are broken in this release. To address https://github.com/Azure/azure-mobile-apps-node/issues/420, I added a [mapParameterValue function](https://github.com/Azure/azure-mobile-apps-node/blob/master/src/data/sqlite/helpers.js#L10) that coerces dates in SQL parameters into an ISO string format but didn't update the column defaults and update trigger. This is fixed in 2.2.2. I will be updating the templates to a new version tonight.

We have end to end tests that would have caught this, but our automation was not set up to run them against the SQLite data provider. We'll fix this.

**Comment by jamesmontemagno** [comment]
@danderson00 I tested this in the latest release and it still appears to be broken, not sure what is going on...

**Comment by danderson00** [comment]
OK cool, I did test this after releasing and it worked OK, but that was at about 1:30AM, so my test may have been somewhat flawed. Thanks for the heads up, I'll look at this now.

**Comment by jamesmontemagno** [comment]
Sounds good, just demoing tomorrow! I can connect it to my SQLAzure I guess though. I tested and as soon as I connected to SQLAzure it worked fine again.

The QuickStart gave me the current 3.0.0

**Comment by danderson00** [comment]
With a simple test, it seems to work OK. The steps I used to test:

- create new Mobile Apps Quickstart from gallery
- download Windows UWP quickstart
- build/run - online works OK
- follow steps [here](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-windows-store-dotnet-get-started-offline-data/) to enable offline sync (except with 2.1.1 of SQLiteStore nuget)
- run to perform initial sync
- add records externally using postman
- refresh client - records are pulled as expected

This flow didn't work with 2.1.1. Are you able to boil the issue down to a simple repro? It's entirely possible there are still issues that aren't picked up in this simple case.

**Comment by jamesmontemagno** [comment]
So I just tried my repo steps, which is how i created the original bug, and it seems to be working now. 

Here are my original repo steps:

* Create new Mobile Apps Quickstart from gallery
* Download Cross Platform todo list: https://github.com/xamarin/dev-days-labs (inside the demos - app-taks, this will have online/offline sync setup), this is an updated version of the default sample.
* Fill in url for azure site
* build/run - Windows App, create item and press add, press sync, shows in portal
* build/run - Android or iOS app
* Press sync
* Windows data will show up
* Insert new todo item from Android/iOS app -> Press sync, will show in portal
* Sync Windows.. new data doesn't show up, but is in portal

I was just testing a different app and it wasn't working, but I wasn't using the default table that was given to me. It looks like this bug pops up only when you create a new table.

So... for the above repo, or I assume yours as well delete the table and then create a new table. That triggered the bug for me.

**Comment by danderson00** [comment]
Yep, I can repro. Will get back to you shortly.

**Comment by danderson00** [comment]
This has been resolved.
